//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public Dersler()
        {
            this.OgrenciDersleri = new HashSet<OgrenciDersleri>();
        }
    
        public int Id { get; set; }
        public string DersAdi { get; set; }
        public string DersKodu { get; set; }
    
        public virtual ICollection<OgrenciDersleri> OgrenciDersleri { get; set; }
    }
}
