//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentManagementEntities : DbContext
    {
        public StudentManagementEntities()
            : base("name=StudentManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dersler> Dersler { get; set; }
        public DbSet<OgrenciDersleri> OgrenciDersleri { get; set; }
        public DbSet<Ogrenciler> Ogrenciler { get; set; }
        public DbSet<Ogretmen> Ogretmen { get; set; }
        public DbSet<Chat> Chat { get; set; }
    }
}
