//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public Ogrenciler()
        {
            this.OgrenciDersleri = new HashSet<OgrenciDersleri>();
            this.Chat = new HashSet<Chat>();
        }
    
        public int Id { get; set; }
        public int OgrenciNo { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string Sifre { get; set; }
        public string EPosta { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<OgrenciDersleri> OgrenciDersleri { get; set; }
        public virtual ICollection<Chat> Chat { get; set; }
    }
}
